### ISSUE TITLE
Feature Request Rotation

### ISSUE THREAD

**Issue by superfrantv** [tommyettinger/IsoVoxel#11]
Hello,

if iam convert some .vox files (creates by FileToVox) the rotation is wrong.
is it possible to add a command for rotation?

and my finished pictures are a lit bit darker/grayer then the original color?

**Comment by tommyettinger** [comment]
What rotation is expected? Could you attach an image of a "right" rotation? This produces 8 directions, but because of the limits of pixels and the diagonal lines that can be smoothly drawn with just pixels, the viewing angle varies slightly between ortho and isometric views. I haven't used FileToVox, and I only heard of it recently as an open source software that might help solve a different issue.

I've tried  a number of things for the color, but since .vox files only have one color per-voxel, not per-face, any renderer has to estimate the change in color for other faces. Depending on the environment, the renders could be too dark or too light... The grayish quality (low saturation) is something I can try to figure out, but there isn't just one right answer here.

**Comment by superfrantv** [comment]
Ok sorry my mistake, the rotation problem comes from FileToVox, the Programm exports the vox file in wrong rotation, so i have to manuelly rerotate every file.

The grayish quality is importener.
thanks for this great work!

**Comment by tommyettinger** [comment]
OK, this should be fixed in 0.0.14, released today. Sorry it took so long!
