### ISSUE TITLE
Support MagicaVoxel 0.98 Frame-Based Animation

### ISSUE THREAD

**Issue by tiaod** [tommyettinger/IsoVoxel#4]

**Comment by tommyettinger** [comment]
Should be possible, though I don't think it's technically possible to emit GIF animations as a result unless the total number of voxel colors is fairly low (at most 63, but possibly less; a GIF can have at most 256 colors in a frame unless hackish techniques are used to cheat that limit). Producing individual frames as PNG files should be possible, but I probably won't pack them into a spritesheet/texture-atlas because every game library and framework has its own preferred format for them.

@tiaod , would the output ideally use the naming convention where the frames are named according to the base .vox model (and facing angle and such, as it does now), followed by `_0.png` for frame 0, `_1.png` for frame 1, etc.? That's what I use in my related PixVoxelAssets project, so it would be easy to bring some of that over (it doesn't parse .vox animated files though; it generates animations).

**Comment by tiaod** [comment]
Yes, producing individual frames as PNG files is enough. But I think the name should be `_00.png`, `_01png`, `_02.png` , etc. Since MagicaVoxel can support up to 24 frames.
Producting gif or spritesheet is not necessary, because there are many tools can convert `.png` files to gif or spiresheets.(eg. Texturepacker). IsoVoxel is awesome, and small is beautiful.

**Comment by tommyettinger** [comment]
This should be all implemented as of the latest release, https://github.com/tommyettinger/IsoVoxel/releases/tag/v0.0.10 . Thanks for using IsoVoxel!

**Comment by tiaod** [comment]
So cute!
![ezgif-1-bd2d1a2169](https://user-images.githubusercontent.com/7500825/38737748-c6fd436c-3f62-11e8-8471-d606ea65265d.gif)
