### ISSUE TITLE
How can we pass optional arguments?

### ISSUE THREAD

**Issue by BeFiveINFO** [tommyettinger/IsoVoxel#8]
Excuse me to ask such a basic question.

I have been wondering how we can pass optional arguments. I have been trying to set the m value like:

```
IsoVoxel.exe character.vox m=3
```

But I always get files in all sizes.

Thank you very much for your help in advance.

**Comment by tommyettinger** [comment]
No problem! I didn't write a full-featured argument handler; IsoVoxel tries to read as many arguments as it can, in the order `IsoVoxel.exe file.vox x y z m o`. That means it needs x, y, and z sizes to be specified before m, for multipliers (unless m is the default, which is 3 already). You don't need to specify later arguments, like o for outlining, but do need to specify earlier ones. An example where you want multpliers 1 through 4 would be `IsoVoxel.exe Red_Fish.vox 12 12 8 4`, because Red_Fish.vox (which you can download [here](https://github.com/tommyettinger/IsoVoxel/blob/master/IsoVoxel/Red_Fish.vox?raw=true)) has x size 12, y size 12, and z size 8, which you can see in MagicaVoxel like so: 
![MagicaVoxel_2019-09-07_19-18-59](https://user-images.githubusercontent.com/160684/64482318-979cfb00-d1a4-11e9-9a4e-025d8ff996e4.png)
 , and the last number `4` is how many multiplied sizes to make, up to the largest with 4 times the size. There isn't currently any way to make IsoVoxel generate less images, but I could maybe make a quick option to put the output in subfolders for each size, so they are separated and unwanted sizes could be quickly deleted with their subfolder. If you only want multiple 3 (which is the default), and don't want to keep multiples 1 and 2, then once I implement the folder option you should be able to just call `IsoVoxel.exe character.vox` or drag-and-drop character.vox onto IsoVoxel.exe , then delete the folders for sizes 1 and 2. I think using folders will be chosen by default, so it will work with drag-and-drop. I did notice that making lots of renders produces quite a lot of files, and defaulting to using folders for different sizes may help clean that up.

**Comment by BeFiveINFO** [comment]
Thank you very much for the detailed explanation!
I would have given up to use voxel for my isometric view game without your software.
Thank you!

**Comment by tommyettinger** [comment]
OK, the folder organization is in a new tiny update, https://github.com/tommyettinger/IsoVoxel/releases/tag/v0.0.13 . I can make tweaks to it if you want, or if something isn't intuitive. I'll close this issue, but feel free to reopen it or comment if you have suggestions for better ways to handle the folders.
